### ISSUE TITLE
Any firmware available?

### ISSUE THREAD

**Issue by elektronika-ba** [xil-se/SX1257-PMOD#7]
Hi,

Is there any firmware available for this device?
I am interested in a simple raw I/Q acquisition and reproduction excercise.

Thanks!

**Comment by kbeckmann** [comment]
I have some quite hacky early bring up code here https://git.xil.se/kbeckmann/SX1257/src/branch/thumbinator-bringup/bringup/Src/main.c

I also wrote some HDL that performs the init sequence and receives the raw 1 bit data here https://git.xil.se/kbeckmann/Kilsyth/src/branch/master/software/kilsyth/applets/sx1257/__init__.py

Please note that these two projects are very hacky, you might be better off writing your own code from scratch.
